service:
  name: healthcheck
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/Lambdas/healtcheck/handler.healtcheck
    events:
      - http:
          method: get
          path: hello
