service:
  name: healthcheck
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}

functions:
  healtcheck:
    handler: src/Lambdas/healtCheck/handler.healtcheck
    events:
      - http:
          method: get
          path: hello
