defauts: &defaults
  working_directory: ~/myorganic
  machine: true

version: 2
jobs:
  unitTest:
    <<: *defaults
    steps:
      - checkout
      - run: chmod +x ./scripts/spinEnv.sh
      - run: ./scripts/spinEnv.sh
      - run: ./scripts/install_packages.sh
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}

      - run: jest
      #TODO only run unit test for deployed lambda
      - save_cache:
          key: source_v1-{{ .Branch }}-{{ epoch }}
          paths:
            - lambdas/healtcheck/node_modules
  e2e:
    <<: *defaults
    steps:
      - checkout
      - run: chmod +x ./scripts/spinEnv.sh
      - run: ./scripts/spinEnv.sh
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}

      - run: cd e2e && jest
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: chmod +x ./scripts/spinEnv.sh
      - run: ./scripts/spinEnv.sh
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}

      - run: ./scripts/credentials.sh $ENV
      - run: ./script/deploy.sh
      #TODO write serverless strategy


workflows:
  version: 2
  staging:
    jobs:
      - unitTest:
          filters:
            branches:
              only: dev
          context: staging
      - e2e:
          requires:
            - unitTest
          filters:
            branches:
              only: dev
          context: staging
      - deploy:
          requires:
            - unitTest
            - e2e
          filters:
            branches:
              only: dev
          context: staging
  prod:
    jobs:
      - unitTest:
          filters:
            branches:
              only: master
          context: production
      - e2e:
          requires:
            - unitTest
          filters:
            branches:
              only: master
          context: production
      - deploy:
          requires:
            - unitTest
            - e2e
          filters:
            branches:
              only: master
          context: production







