defauts: &defaults
  working_directory: ~/myorganic
  machine: true

version: 2
jobs:
  unitTest:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/spinEnv.sh unitTest
      - run: ./scripts/install_packages.sh install
      - run: ./scripts/unit_test.sh
      #TODO only run unit test for deployed lambda
      - save_cache:
          key: source_v1-{{ .Branch }}-{{ epoch }}
          paths:
            - lambdas/healtcheck/node_modules
  e2e:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/spinEnv.sh e2e
      - run: ./scripts/install_packages.sh install
      - run:
          name: Serverless Framework Offline
          command: sls offline
          background: true
      - run: sleep 20
      - run: STAGE='local' npm run e2eLocal
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/spinEnv.sh deploy
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-

      - run: ./scripts/credentials.sh $ENV
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  staging:
    jobs:
      - unitTest:
          filters:
            branches:
              only: dev
          context: staging
      - e2e:
          requires:
            - unitTest
          filters:
            branches:
              only: dev
          context: staging
      - deploy:
          requires:
            - unitTest
            - e2e
          filters:
            branches:
              only: dev
          context: staging
  prod:
    jobs:
      - unitTest:
          filters:
            branches:
              only: master
          context: production
      - e2e:
          requires:
            - unitTest
          filters:
            branches:
              only: master
          context: production
      - deploy:
          requires:
            - unitTest
            - e2e
          filters:
            branches:
              only: master
          context: production







